### ISSUE TITLE
Cannot run commands 

### ISSUE THREAD

**Issue by subsidel** [tauri-apps/tauri-vscode#163]
Hi,

Not sure if I've set something up wrong or if it's an issue with running in this way.

I have a tauri project that works fine when running the tauri cli via npm in the way that the template tool creates it (eg `npm run tauri dev`) but when in a workspace with just that project, running the command "Tauri: Dev" from the command pallet gives the following error dialog:

![Error dialog saying Command: 'Tauri: Dev' resulted in an error (command 'tauri.dev' not found)](https://user-images.githubusercontent.com/1258370/188196694-a665ef3d-57ff-48fc-b291-463daea6c469.png)

A similar dialog shows for all the other commands too.
I have tried installing `@tauri-apps/cli` globally in case this was needed, but this doesn't seem to affect anything.

Setup:
Windows 11 with WSL running Ubuntu 20.04
npm: 8.11.0
node: v16.16.0
cargo: cargo 1.62.1 (a748cf5a3 2022-06-08)
rustc: rustc 1.62.1 (e092d0b6b 2022-07-16)
VSCode: 1.70.2
tauri-vscode: v0.1.6 Extension is enabled on 'WSL: Ubuntu-20.04'

**Comment by amrbashir** [comment]
could you try this suggestion https://stackoverflow.com/a/56129225 and see if you can get more info about the error?

**Comment by subsidel** [comment]
yep, I see the following:

```
mainThreadExtensionService.ts:111 Activating extension 'tauri-apps.tauri-vscode' failed: Cannot find module 'concat-map'
Require stack:
- /home/joey/.vscode-server/extensions/tauri-apps.tauri-vscode-0.1.6/node_modules/brace-expansion/index.js
- /home/joey/.vscode-server/extensions/tauri-apps.tauri-vscode-0.1.6/node_modules/minimatch/minimatch.js
- /home/joey/.vscode-server/extensions/tauri-apps.tauri-vscode-0.1.6/node_modules/glob/glob.js
- /home/joey/.vscode-server/extensions/tauri-apps.tauri-vscode-0.1.6/out/extension.js
- /home/joey/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/loader.js
- /home/joey/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/bootstrap-amd.js
- /home/joey/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/bootstrap-fork.js.
```
