### ISSUE TITLE
Getting error: Couldn't detect package manager for current project.

### ISSUE THREAD

**Issue by bluenote10** [tauri-apps/tauri-vscode#227]
I'm very new to Tauri, and I was just trying out what the VSCode can do. However, when I execute any tauri command from the command palette, I'm simply getting the error: _Couldn't detect package manager for current project._

(in lower right status):

![image](https://github.com/tauri-apps/tauri-vscode/assets/3620703/c8062d0f-5fb2-4d52-a4c0-d6954865d2fc)

The VSCode's output channel for `tauri` is empty, so no further hints there either.

The code for which I was trying the extension is: https://github.com/michalvavra/tauri-leptos-example

I might well be that I'm missing some prerequisite -- are they documented somewhere?

**Comment by amrbashir** [comment]
did you install `tauri-cli` using `cargo install tauri-cli`?

**Comment by bluenote10** [comment]
No, so far I prefer using it via `npx @tauri-apps/cli`. I thought either way is supported officially?

**Comment by FabianLars** [comment]
> I thought either way is supported officially?

Generally yes, but not by this extension yet

**Comment by bluenote10** [comment]
I can confirm now that installing the tauri cli via cargo fixed the issue. Perhaps it makes sense to mention this in the extension description?
