### ISSUE TITLE
Suggest adding a link to VScode marketplace.

### ISSUE THREAD

**Issue by 119311** [tauri-apps/tauri-vscode#236]
How about adding a link to the marketplace on the github page?

Of course you all know this link, but could you please add something like the following.
[link to marketplace](https://marketplace.visualstudio.com/items?itemName=tauri-apps.tauri-vscode)

**Comment by amrbashir** [comment]
Sounds like a good idea preferably using a badge from shields.io, would you like to make a PR? We would appreciate it, thanks :heart:

**Comment by 119311** [comment]
Thanks @amrbashir.

The truth is I'd love to send you a PR, but the solution I'm trying to figure out is to edit the About in the upper right hand corner of the screen and add a link like the one in the picture.

I made changes to the one I forked myself, but couldn't get it to create a PR...

Probably because I'm not in contributors, but if you don't mind, could you please edit it directly

![image](https://github.com/tauri-apps/tauri-vscode/assets/92527171/4af4e56a-6e58-44bc-a2cd-5c68a3764b25)

**Comment by 119311** [comment]
thanks @amrbashir 

I see.
I'll try with shields.io.

**Comment by amrbashir** [comment]
@119311 thanks I added it in the repo description as per your suggestion.

**Comment by amrbashir** [comment]
Feel free to open a PR for the README if you want.
