### ISSUE TITLE
Unable to load schema error

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-vscode#53]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/35242872/116553067-02f78b80-a8fa-11eb-995e-8c7fb0d90d12.png">

**Comment by nothingismagick** [comment]
Do we just need to cut a fresh release? I am asking, because I just reinstalled the plugin and get that error.

**Comment by lucasfernog** [comment]
I've merged the covector PR but the publish failed :( i'll fix this.

**Comment by lucasfernog** [comment]
Actually the CI here needs improvements - i forgot to manually open a PR to the release branch :D

**Comment by lucasfernog** [comment]
v0.1.0 published https://marketplace.visualstudio.com/items?itemName=tauri-apps.tauri-vscode
but i can't see it on VSCode yet :(

**Comment by nothingismagick** [comment]
I can.
![image](https://user-images.githubusercontent.com/35242872/116556822-2f150b80-a8fe-11eb-9c88-6084c6f1efa3.png)

**Comment by nothingismagick** [comment]
But am seeing the same error

![image](https://user-images.githubusercontent.com/35242872/116557226-887d3a80-a8fe-11eb-9269-001318ed17ba.png)

**Comment by lucasfernog** [comment]
Seems like I used the wrong link; it should've been the raw content link :/

**Comment by lucasfernog** [comment]
v0.1.1 is up. I couldn't find it in my VSCode because i use the open source build and it didn't have the marketplace enabled :P

**Comment by nothingismagick** [comment]
cheers! works now
