### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-vscode#59]
It's nice that there aren't any errors, but what all can be done with this extension?

**Comment by Chaostheorie** [comment]
AFAIK as I know this application can run tauri scripts, such as `dev`.

**Comment by nothingismagick** [comment]
It can also give you information about the available keys in `tauri.conf.json`.

**Comment by nothingismagick** [comment]
@Chaostheorie - are you making a Tauri version of Pentagame???

**Comment by Chaostheorie** [comment]
No. When I have some motivation for pentagame related development, it's gonna be going into [pentagame-engine](https://gitlab.cobalt.rocks/cobalt/pentagame-engine) for the time being.
