### ISSUE TITLE
Release for VSCodium

### ISSUE THREAD

**Issue by Chaostheorie** [tauri-apps/tauri-vscode#64]
I've recently successfully built this application, and I'm using it in [VSCodium](https://github.com/VSCodium/vscodium), a telemetry free variant of VSCode ([differences](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code)). This variety uses  [open-vsx.org](https://open-vsx.org/) as extension store, see [related issue](https://github.com/microsoft/vscode/issues/31168). 

I wanted to request the release of tauri-vscode on open-vsx too, since I think this extension can be helpful to more developers. There's also the point that VSCodium users have to build the extension manually ATM, which means they won't get notified about updates and have to always rebuild manually. 

It would be nice to have this extension there too. There's also a [GitHub action](https://github.com/HaaLeo/publish-vscode-extension#publish-vs-code-extension--github-action) for automating this process with both stores.

Related Links:
- [openvsx - how to publish an extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension)

Note: English is not my mother tongue, but I hope the text is understandable.

**Comment by nothingismagick** [comment]
Great idea! Thanks

**Comment by DoodlesEpic** [comment]
Just bumping this. I feel it's a very important thing for Tauri, especially because Tauri is very big on being open-source, only having the extension for the closed source code editor is kind of a bummer.

**Comment by REALERvolker1** [comment]
Another bump is necessary
![image](https://user-images.githubusercontent.com/73304952/191867397-972c6042-e040-43b3-a9ec-5d804ff9fb9e.png)

**Comment by boldandbrad** [comment]
Please consider this! Would make my workflow much simpler!

**Comment by Beanow** [comment]
Hi, we've started to process to get set up with publishing to open-vsx.org.
Thank you for the detailed pointers @Chaostheorie.

Although hopefully we can actually use it, and doesn't go away in the near future!
https://blogs.eclipse.org/post/john-kellerman/help-us-sustain-open-vsxorg

**Comment by amrbashir** [comment]
We apologize for taking this long to tackle this issue, but the extension is published now and working quite well 🎉 .

**Comment by Chaostheorie** [comment]
Thank you, let's hope open-vsx.org stays up.
